//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/free6om/Documents/open-source/j2objc/j2objc/testing/mockito/build_result/java/org/mockito/mock/MockName.java
//

#ifndef _OrgMockitoMockMockName_H_
#define _OrgMockitoMockMockName_H_

#include "J2ObjC_header.h"

@protocol OrgMockitoMockMockName < NSObject, JavaObject >

- (NSString *)description;

- (jboolean)isDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoMockMockName)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoMockMockName)

#endif // _OrgMockitoMockMockName_H_
