//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/free6om/Documents/open-source/j2objc/j2objc/testing/mockito/build_result/java/org/mockito/MockingDetails.java
//

#ifndef _OrgMockitoMockingDetails_H_
#define _OrgMockitoMockingDetails_H_

#include "J2ObjC_header.h"

@protocol OrgMockitoMockingDetails < NSObject, JavaObject >

- (jboolean)isMock;

- (jboolean)isSpy;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoMockingDetails)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoMockingDetails)

#endif // _OrgMockitoMockingDetails_H_
