//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/free6om/Documents/open-source/j2objc/j2objc/testing/mockito/build_result/java/org/mockito/MockSettings.java
//

#ifndef _OrgMockitoMockSettings_H_
#define _OrgMockitoMockSettings_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@class IOSObjectArray;
@protocol OrgMockitoStubbingAnswer;

@protocol OrgMockitoMockSettings < JavaIoSerializable, NSObject, JavaObject >

- (id<OrgMockitoMockSettings>)extraInterfacesWithIOSClassArray:(IOSObjectArray *)interfaces;

- (id<OrgMockitoMockSettings>)nameWithNSString:(NSString *)name;

- (id<OrgMockitoMockSettings>)spiedInstanceWithId:(id)instance;

- (id<OrgMockitoMockSettings>)defaultAnswerWithOrgMockitoStubbingAnswer:(id<OrgMockitoStubbingAnswer>)defaultAnswer;

- (id<OrgMockitoMockSettings>)serializable;

- (id<OrgMockitoMockSettings>)verboseLogging;

- (id<OrgMockitoMockSettings>)invocationListenersWithOrgMockitoListenersInvocationListenerArray:(IOSObjectArray *)listeners;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoMockSettings)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoMockSettings)

#endif // _OrgMockitoMockSettings_H_
