//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/free6om/Documents/open-source/j2objc/j2objc/junit/build_result/java/org/junit/internal/JUnitSystem.java
//

#ifndef _OrgJunitInternalJUnitSystem_H_
#define _OrgJunitInternalJUnitSystem_H_

#include "J2ObjC_header.h"

@class JavaIoPrintStream;

@protocol OrgJunitInternalJUnitSystem < NSObject, JavaObject >

- (JavaIoPrintStream *)out;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitInternalJUnitSystem)

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitInternalJUnitSystem)

#endif // _OrgJunitInternalJUnitSystem_H_
