//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/InheritableThreadLocal.java
//

#ifndef _JavaLangInheritableThreadLocal_H_
#define _JavaLangInheritableThreadLocal_H_

#include "J2ObjC_header.h"
#include "java/lang/ThreadLocal.h"

@class JavaLangThread;

@interface JavaLangInheritableThreadLocal : JavaLangThreadLocal

#pragma mark Public

- (instancetype)init;

#pragma mark Protected

- (id)childValueWithId:(id)parentValue;

#pragma mark Package-Private

- (JavaLangThreadLocal_Values *)initializeValuesWithJavaLangThread:(JavaLangThread *)current OBJC_METHOD_FAMILY_NONE;

- (JavaLangThreadLocal_Values *)valuesWithJavaLangThread:(JavaLangThread *)current;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaLangInheritableThreadLocal)

FOUNDATION_EXPORT void JavaLangInheritableThreadLocal_init(JavaLangInheritableThreadLocal *self);

FOUNDATION_EXPORT JavaLangInheritableThreadLocal *new_JavaLangInheritableThreadLocal_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaLangInheritableThreadLocal)

#endif // _JavaLangInheritableThreadLocal_H_
