//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/ThreadLocal.java
//

#ifndef _JavaLangThreadLocal_H_
#define _JavaLangThreadLocal_H_

#include "J2ObjC_header.h"

@class JavaLangThread;
@class JavaLangThreadLocal_Values;

@interface JavaLangThreadLocal : NSObject

#pragma mark Public

- (instancetype)init;

- (id)get;

- (void)remove;

- (void)setWithId:(id)value;

#pragma mark Protected

- (id)initialValue OBJC_METHOD_FAMILY_NONE;

#pragma mark Package-Private

- (JavaLangThreadLocal_Values *)initializeValuesWithJavaLangThread:(JavaLangThread *)current OBJC_METHOD_FAMILY_NONE;

- (JavaLangThreadLocal_Values *)valuesWithJavaLangThread:(JavaLangThread *)current;

@end

J2OBJC_STATIC_INIT(JavaLangThreadLocal)

FOUNDATION_EXPORT void JavaLangThreadLocal_init(JavaLangThreadLocal *self);

FOUNDATION_EXPORT JavaLangThreadLocal *new_JavaLangThreadLocal_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaLangThreadLocal)

@interface JavaLangThreadLocal_Values : NSObject

#pragma mark Package-Private

- (instancetype)init;

- (instancetype)initWithJavaLangThreadLocal_Values:(JavaLangThreadLocal_Values *)fromParent;

- (void)addWithJavaLangThreadLocal:(JavaLangThreadLocal *)key
                            withId:(id)value;

- (id)getAfterMissWithJavaLangThreadLocal:(JavaLangThreadLocal *)key;

- (void)putWithJavaLangThreadLocal:(JavaLangThreadLocal *)key
                            withId:(id)value;

- (void)removeWithJavaLangThreadLocal:(JavaLangThreadLocal *)key;

@end

J2OBJC_STATIC_INIT(JavaLangThreadLocal_Values)

FOUNDATION_EXPORT void JavaLangThreadLocal_Values_init(JavaLangThreadLocal_Values *self);

FOUNDATION_EXPORT JavaLangThreadLocal_Values *new_JavaLangThreadLocal_Values_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaLangThreadLocal_Values_initWithJavaLangThreadLocal_Values_(JavaLangThreadLocal_Values *self, JavaLangThreadLocal_Values *fromParent);

FOUNDATION_EXPORT JavaLangThreadLocal_Values *new_JavaLangThreadLocal_Values_initWithJavaLangThreadLocal_Values_(JavaLangThreadLocal_Values *fromParent) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaLangThreadLocal_Values)

#endif // _JavaLangThreadLocal_H_
