//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/crypto/Mac.java
//

#ifndef _JavaxCryptoMac_H_
#define _JavaxCryptoMac_H_

#include "J2ObjC_header.h"

@class IOSByteArray;
@class JavaNioByteBuffer;
@class JavaSecurityProvider;
@class JavaxCryptoMacSpi;
@protocol JavaSecurityKey;
@protocol JavaSecuritySpecAlgorithmParameterSpec;

@interface JavaxCryptoMac : NSObject < NSCopying >

#pragma mark Public

- (id)clone;

- (IOSByteArray *)doFinal;

- (IOSByteArray *)doFinalWithByteArray:(IOSByteArray *)input;

- (void)doFinalWithByteArray:(IOSByteArray *)output
                     withInt:(jint)outOffset;

- (NSString *)getAlgorithm;

+ (JavaxCryptoMac *)getInstanceWithNSString:(NSString *)algorithm;

+ (JavaxCryptoMac *)getInstanceWithNSString:(NSString *)algorithm
                   withJavaSecurityProvider:(JavaSecurityProvider *)provider;

+ (JavaxCryptoMac *)getInstanceWithNSString:(NSString *)algorithm
                               withNSString:(NSString *)provider;

- (jint)getMacLength;

- (JavaSecurityProvider *)getProvider;

- (void)init__WithJavaSecurityKey:(id<JavaSecurityKey>)key OBJC_METHOD_FAMILY_NONE;

- (void)init__WithJavaSecurityKey:(id<JavaSecurityKey>)key
withJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)params OBJC_METHOD_FAMILY_NONE;

- (void)reset;

- (void)updateWithByte:(jbyte)input;

- (void)updateWithByteArray:(IOSByteArray *)input;

- (void)updateWithByteArray:(IOSByteArray *)input
                    withInt:(jint)offset
                    withInt:(jint)len;

- (void)updateWithJavaNioByteBuffer:(JavaNioByteBuffer *)input;

#pragma mark Protected

- (instancetype)initWithJavaxCryptoMacSpi:(JavaxCryptoMacSpi *)macSpi
                 withJavaSecurityProvider:(JavaSecurityProvider *)provider
                             withNSString:(NSString *)algorithm;

@end

J2OBJC_STATIC_INIT(JavaxCryptoMac)

FOUNDATION_EXPORT void JavaxCryptoMac_initWithJavaxCryptoMacSpi_withJavaSecurityProvider_withNSString_(JavaxCryptoMac *self, JavaxCryptoMacSpi *macSpi, JavaSecurityProvider *provider, NSString *algorithm);

FOUNDATION_EXPORT JavaxCryptoMac *new_JavaxCryptoMac_initWithJavaxCryptoMacSpi_withJavaSecurityProvider_withNSString_(JavaxCryptoMacSpi *macSpi, JavaSecurityProvider *provider, NSString *algorithm) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JavaxCryptoMac *JavaxCryptoMac_getInstanceWithNSString_(NSString *algorithm);

FOUNDATION_EXPORT JavaxCryptoMac *JavaxCryptoMac_getInstanceWithNSString_withNSString_(NSString *algorithm, NSString *provider);

FOUNDATION_EXPORT JavaxCryptoMac *JavaxCryptoMac_getInstanceWithNSString_withJavaSecurityProvider_(NSString *algorithm, JavaSecurityProvider *provider);

J2OBJC_TYPE_LITERAL_HEADER(JavaxCryptoMac)

#endif // _JavaxCryptoMac_H_
