//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/crypto/MacSpi.java
//

#ifndef _JavaxCryptoMacSpi_H_
#define _JavaxCryptoMacSpi_H_

#include "J2ObjC_header.h"

@class IOSByteArray;
@class JavaNioByteBuffer;
@protocol JavaSecurityKey;
@protocol JavaSecuritySpecAlgorithmParameterSpec;

@interface JavaxCryptoMacSpi : NSObject

#pragma mark Public

- (instancetype)init;

- (id)clone;

#pragma mark Protected

- (IOSByteArray *)engineDoFinal;

- (jint)engineGetMacLength;

- (void)engineInitWithJavaSecurityKey:(id<JavaSecurityKey>)key
withJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)params;

- (void)engineReset;

- (void)engineUpdateWithByte:(jbyte)input;

- (void)engineUpdateWithByteArray:(IOSByteArray *)input
                          withInt:(jint)offset
                          withInt:(jint)len;

- (void)engineUpdateWithJavaNioByteBuffer:(JavaNioByteBuffer *)input;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxCryptoMacSpi)

FOUNDATION_EXPORT void JavaxCryptoMacSpi_init(JavaxCryptoMacSpi *self);

J2OBJC_TYPE_LITERAL_HEADER(JavaxCryptoMacSpi)

#endif // _JavaxCryptoMacSpi_H_
