//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/crypto/ShortBufferException.java
//

#ifndef _JavaxCryptoShortBufferException_H_
#define _JavaxCryptoShortBufferException_H_

#include "J2ObjC_header.h"
#include "java/security/GeneralSecurityException.h"

@interface JavaxCryptoShortBufferException : JavaSecurityGeneralSecurityException

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)msg;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxCryptoShortBufferException)

FOUNDATION_EXPORT void JavaxCryptoShortBufferException_initWithNSString_(JavaxCryptoShortBufferException *self, NSString *msg);

FOUNDATION_EXPORT JavaxCryptoShortBufferException *new_JavaxCryptoShortBufferException_initWithNSString_(NSString *msg) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaxCryptoShortBufferException_init(JavaxCryptoShortBufferException *self);

FOUNDATION_EXPORT JavaxCryptoShortBufferException *new_JavaxCryptoShortBufferException_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaxCryptoShortBufferException)

#endif // _JavaxCryptoShortBufferException_H_
