//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/free6om/Documents/open-source/j2objc/j2objc/junit/build_result/java/org/junit/runner/Describable.java
//

#ifndef _OrgJunitRunnerDescribable_H_
#define _OrgJunitRunnerDescribable_H_

#include "J2ObjC_header.h"

@class OrgJunitRunnerDescription;

@protocol OrgJunitRunnerDescribable < NSObject, JavaObject >

- (OrgJunitRunnerDescription *)getDescription;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRunnerDescribable)

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnerDescribable)

#endif // _OrgJunitRunnerDescribable_H_
