//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/LinkedList.java
//

#ifndef _JavaUtilLinkedList_H_
#define _JavaUtilLinkedList_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"
#include "java/util/AbstractSequentialList.h"
#include "java/util/Deque.h"
#include "java/util/List.h"
#include "java/util/Queue.h"

@class IOSObjectArray;
@class JavaUtilLinkedList_Link;
@protocol JavaUtilCollection;
@protocol JavaUtilIterator;
@protocol JavaUtilListIterator;

@interface JavaUtilLinkedList : JavaUtilAbstractSequentialList < JavaUtilList, JavaUtilDeque, JavaUtilQueue, NSCopying, JavaIoSerializable > {
 @public
  jint size_;
  JavaUtilLinkedList_Link *voidLink_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (jboolean)addWithId:(id)object;

- (void)addWithInt:(jint)location
            withId:(id)object;

- (jboolean)addAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (jboolean)addAllWithInt:(jint)location
   withJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (void)addFirstWithId:(id)object;

- (void)addLastWithId:(id)object;

- (void)clear;

- (id)clone;

- (jboolean)containsWithId:(id)object;

- (id<JavaUtilIterator>)descendingIterator;

- (id)element;

- (id)getWithInt:(jint)location;

- (id)getFirst;

- (id)getLast;

- (jint)indexOfWithId:(id)object;

- (jint)lastIndexOfWithId:(id)object;

- (id<JavaUtilListIterator>)listIteratorWithInt:(jint)location;

- (jboolean)offerWithId:(id)o;

- (jboolean)offerFirstWithId:(id)e;

- (jboolean)offerLastWithId:(id)e;

- (id)peek;

- (id)peekFirst;

- (id)peekLast;

- (id)poll;

- (id)pollFirst;

- (id)pollLast;

- (id)pop;

- (void)pushWithId:(id)e;

- (id)remove;

- (id)removeWithInt:(jint)location;

- (jboolean)removeWithId:(id)object;

- (id)removeFirst;

- (jboolean)removeFirstOccurrenceWithId:(id)o;

- (id)removeLast;

- (jboolean)removeLastOccurrenceWithId:(id)o;

- (id)setWithInt:(jint)location
          withId:(id)object;

- (jint)size;

- (IOSObjectArray *)toArray;

- (IOSObjectArray *)toArrayWithNSObjectArray:(IOSObjectArray *)contents;

#pragma mark Protected

- (void)dealloc;

#pragma mark Package-Private


@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilLinkedList)

J2OBJC_FIELD_SETTER(JavaUtilLinkedList, voidLink_, JavaUtilLinkedList_Link *)

FOUNDATION_EXPORT void JavaUtilLinkedList_init(JavaUtilLinkedList *self);

FOUNDATION_EXPORT JavaUtilLinkedList *new_JavaUtilLinkedList_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void JavaUtilLinkedList_initWithJavaUtilCollection_(JavaUtilLinkedList *self, id<JavaUtilCollection> collection);

FOUNDATION_EXPORT JavaUtilLinkedList *new_JavaUtilLinkedList_initWithJavaUtilCollection_(id<JavaUtilCollection> collection) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilLinkedList)

@interface JavaUtilLinkedList_Link : NSObject {
 @public
  id data_;
  __weak JavaUtilLinkedList_Link *previous_;
  JavaUtilLinkedList_Link *next_;
}

#pragma mark Package-Private

- (instancetype)initWithId:(id)o
withJavaUtilLinkedList_Link:(JavaUtilLinkedList_Link *)p
withJavaUtilLinkedList_Link:(JavaUtilLinkedList_Link *)n;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilLinkedList_Link)

J2OBJC_FIELD_SETTER(JavaUtilLinkedList_Link, data_, id)
J2OBJC_FIELD_SETTER(JavaUtilLinkedList_Link, next_, JavaUtilLinkedList_Link *)

FOUNDATION_EXPORT void JavaUtilLinkedList_Link_initWithId_withJavaUtilLinkedList_Link_withJavaUtilLinkedList_Link_(JavaUtilLinkedList_Link *self, id o, JavaUtilLinkedList_Link *p, JavaUtilLinkedList_Link *n);

FOUNDATION_EXPORT JavaUtilLinkedList_Link *new_JavaUtilLinkedList_Link_initWithId_withJavaUtilLinkedList_Link_withJavaUtilLinkedList_Link_(id o, JavaUtilLinkedList_Link *p, JavaUtilLinkedList_Link *n) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilLinkedList_Link)

#endif // _JavaUtilLinkedList_H_
