//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/free6om/Documents/open-source/j2objc/j2objc/testing/mockito/build_result/java/org/mockito/internal/listeners/MockingProgressListener.java
//

#ifndef _OrgMockitoInternalListenersMockingProgressListener_H_
#define _OrgMockitoInternalListenersMockingProgressListener_H_

#include "J2ObjC_header.h"

@protocol OrgMockitoInternalListenersMockingProgressListener < NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalListenersMockingProgressListener)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalListenersMockingProgressListener)

#endif // _OrgMockitoInternalListenersMockingProgressListener_H_
