//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/free6om/Documents/open-source/j2objc/j2objc/testing/mockito/build_result/java/org/mockito/internal/exceptions/VerificationAwareInvocation.java
//

#ifndef _OrgMockitoInternalExceptionsVerificationAwareInvocation_H_
#define _OrgMockitoInternalExceptionsVerificationAwareInvocation_H_

#include "J2ObjC_header.h"
#include "org/mockito/invocation/DescribedInvocation.h"

@protocol OrgMockitoInternalExceptionsVerificationAwareInvocation < OrgMockitoInvocationDescribedInvocation, NSObject, JavaObject >

- (jboolean)isVerified;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalExceptionsVerificationAwareInvocation)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalExceptionsVerificationAwareInvocation)

#endif // _OrgMockitoInternalExceptionsVerificationAwareInvocation_H_
