//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/free6om/Documents/open-source/j2objc/j2objc/testing/mockito/build_result/java/org/mockito/internal/matchers/VarargMatcher.java
//

#ifndef _OrgMockitoInternalMatchersVarargMatcher_H_
#define _OrgMockitoInternalMatchersVarargMatcher_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@protocol OrgMockitoInternalMatchersVarargMatcher < JavaIoSerializable, NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalMatchersVarargMatcher)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalMatchersVarargMatcher)

#endif // _OrgMockitoInternalMatchersVarargMatcher_H_
