//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/free6om/Documents/open-source/j2objc/j2objc/testing/mockito/build_result/java/org/mockito/invocation/Location.java
//

#ifndef _OrgMockitoInvocationLocation_H_
#define _OrgMockitoInvocationLocation_H_

#include "J2ObjC_header.h"

@protocol OrgMockitoInvocationLocation < NSObject, JavaObject >

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInvocationLocation)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInvocationLocation)

#endif // _OrgMockitoInvocationLocation_H_
